### ISSUE TITLE
页面设计器：完成初步框架

### ISSUE THREAD

**Issue by IlhamTahir** [Orginone/oiocns-react#127]
单位管理员可以在首页添加新页面，在新页面中插入商品展示组件，该组件展示内容通过关联表单及字段完成，页面包含商品列表、搜索、分类、商品详情。注意：不能定制化做该页面，需要在设计器框架中，以组件方式提供。

## 任务列表

- [x] 原型设计，确定需求范围 [原型图](https://github.com/Orginone/oiocns-react/files/12454162/-.1.pdf)
- [x] 页面管理静态页面
- [x] 页面管理配置数据对接
- [x] 页面设计器框架页面
- [ ] 商品组件数据绑定配置

**Comment by IlhamTahir** [comment]
商品列表参考：

![image](https://github.com/Orginone/oiocns-react/assets/5896572/65c0484d-13b5-4903-8b8a-f0a58b1799a9)

设计图：
https://www.figma.com/file/itZy6LY4VJAzzkd1mLZmVQ/%E5%85%AC%E7%9B%8A%E4%BA%91?type=design&node-id=429%3A1161&mode=design&t=Iut15sgR1rxwCkhD-1

**Comment by panzhaohui** [comment]
尽快把动态数据，和表单数据接通。

**Comment by IlhamTahir** [comment]
> 尽快把动态数据，和表单数据接通。

好友圈动态应该是系统性的数据，现已提交给杨老师编写数据操作层。
这个任务是给页面设计器做整体框架，把表单数据与页面数据做一个打通机制。

**Comment by IlhamTahir** [comment]
[](url)

**Comment by IlhamTahir** [comment]
[页面设计器-迭代1.pdf](https://github.com/Orginone/oiocns-react/files/12454162/-.1.pdf)
