### ISSUE TITLE
 规则设计器完善可用性

### ISSUE THREAD

**Issue by IlhamTahir** [Orginone/oiocns-react#129]
规则设计器：
提交时初始化字段值（序列、当前时间、指定值）
中间审批时更新字段值（当前时间、指定值）
完成审批时更新字段值（当前时间、指定值）

**Comment by cSen1213** [comment]
提交时初始化字段值（当前时间、指定值）：当前版本已支持
序列：为防止重复，无法前端自动生成，须通过请求接口获取；或者使用uuid生成
