### ISSUE TITLE
优化打包命令

### ISSUE THREAD

**Issue by IlhamTahir** [Orginone/oiocns-react#130]
现象：当前打包过程达到15分钟，并伴有内存溢出问题
解决方案：
需要排查Vite打包配置及其rollup配置。
优化不规范的依赖引入

目标：
打包时间控制在5分钟之内。

**Comment by zhpp02** [comment]
- [ ] 分析排查项目依赖包
- [ ] react，react-dom，antd相关依赖走cdn
- [ ] Vite打包配置及rollup配置
- [ ] 优化不规范的依赖引入
