### ISSUE TITLE
README更新

### ISSUE THREAD

**Issue by IlhamTahir** [Orginone/oiocns-react#136]
- [x] 项目目录结构更新
- [x] 参与贡献规则
- [x] 完善其他规则信息
- [x] 完善迭代规则

**Comment by panzhaohui** [comment]
代码目录介绍，要把重要目录介绍清楚，无关紧要的可以省略。

**Comment by IlhamTahir** [comment]
> 代码目录介绍，要把重要目录介绍清楚，无关紧要的可以省略。

好的！
